<?php
/**
 * install.php — First-run setup wizard
 * Creates the SQLite database file, tables, and admin user.
 * Delete or rename this file after installation for security.
 */

define('DB_PATH',      __DIR__ . '/database/restaurant_pos.db');
define('INSTALL_LOCK', __DIR__ . '/database/installed.lock');
define('URL_CONFIG',   __DIR__ . '/database/base_url.php');

// ── If already installed, redirect to app ──────────────────────────────────
if (file_exists(INSTALL_LOCK)) {
    header('Location: index.php');
    exit;
}

$errors  = [];
$success = false;
$step    = isset($_POST['step']) ? (int)$_POST['step'] : 1;

// ── Auto-detect a sensible default base URL ────────────────────────────────
function guessBaseUrl(): string {
    $scheme = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ? 'https' : 'http';
    $host   = $_SERVER['HTTP_HOST'] ?? 'localhost';
    // SCRIPT_NAME is /some/path/install.php — strip the filename to get the folder
    $path   = rtrim(dirname($_SERVER['SCRIPT_NAME'] ?? ''), '/\\');
    return $scheme . '://' . $host . ($path === '' ? '' : $path);
}

// ── Process form ───────────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $admin_user = trim($_POST['admin_user'] ?? 'admin');
    $admin_pass = trim($_POST['admin_pass'] ?? '');
    $confirm    = trim($_POST['confirm_pass'] ?? '');
    $app_name   = trim($_POST['app_name'] ?? 'My Restaurant');
    $lang = $_POST['language'] ?? 'en';
    $language = in_array($lang, ['en','ar']) ? $lang : 'en';
    $currency   = trim($_POST['currency'] ?? 'USD');
    $base_url   = rtrim(trim($_POST['base_url'] ?? guessBaseUrl()), '/');

    $symbols = ['USD'=>'$','IQD'=>' د.ع ','SAR'=>'r.s','AED'=>'d.e','EUR'=>'€','GBP'=>'£'];
    $currency_symbol = $symbols[$currency] ?? $currency;

    if (!$admin_user)             $errors[] = 'Admin username is required.';
    if (strlen($admin_pass) < 4)  $errors[] = 'Password must be at least 4 characters.';
    if ($admin_pass !== $confirm)  $errors[] = 'Passwords do not match.';
    if (!$app_name)               $errors[] = 'Restaurant name is required.';
    if (!preg_match('#^https?://#i', $base_url)) $errors[] = 'Base URL must start with http:// or https://';

    if (!extension_loaded('pdo_sqlite')) {
        $errors[] = 'PHP PDO SQLite extension is not enabled. Enable pdo_sqlite in php.ini.';
    }

    if (empty($errors)) {
        // Create database directory
        $dbDir = dirname(DB_PATH);
        if (!is_dir($dbDir)) {
            mkdir($dbDir, 0755, true);
        }

        // ── Save base URL to config file ──
        $urlConfigContent = "<?php\n// Auto-generated by install.php\ndefine('CONFIGURED_BASE_URL', " . var_export($base_url, true) . ");\n";
        file_put_contents(URL_CONFIG, $urlConfigContent);

        try {
            $db = new PDO('sqlite:' . DB_PATH, null, null, [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]);

            // Enable WAL mode and foreign keys
            $db->exec('PRAGMA journal_mode=WAL');
            $db->exec('PRAGMA foreign_keys=ON');

            // ── Create tables ──
            $db->exec("
                CREATE TABLE IF NOT EXISTS users (
                    id         INTEGER PRIMARY KEY AUTOINCREMENT,
                    username   TEXT NOT NULL UNIQUE,
                    password   TEXT NOT NULL,
                    created_at TEXT NOT NULL DEFAULT (datetime('now'))
                );

                CREATE TABLE IF NOT EXISTS settings (
                    key   TEXT PRIMARY KEY,
                    value TEXT
                );

                CREATE TABLE IF NOT EXISTS items (
                    id         INTEGER PRIMARY KEY AUTOINCREMENT,
                    name_en    TEXT NOT NULL,
                    name_ar    TEXT NOT NULL,
                    price      REAL NOT NULL,
                    photo      TEXT,
                    active     INTEGER DEFAULT 1,
                    created_at TEXT NOT NULL DEFAULT (datetime('now'))
                );

                CREATE TABLE IF NOT EXISTS orders (
                    id           INTEGER PRIMARY KEY AUTOINCREMENT,
                    order_number TEXT NOT NULL,
                    subtotal     REAL NOT NULL,
                    discount     REAL DEFAULT 0,
                    total        REAL NOT NULL,
                    notes        TEXT,
                    created_at   TEXT NOT NULL DEFAULT (datetime('now'))
                );

                CREATE TABLE IF NOT EXISTS order_items (
                    id         INTEGER PRIMARY KEY AUTOINCREMENT,
                    order_id   INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                    item_id    INTEGER NOT NULL,
                    item_name  TEXT NOT NULL,
                    item_price REAL NOT NULL,
                    quantity   INTEGER NOT NULL DEFAULT 1
                );
            ");

            // ── Seed default settings ──
            $defaults = [
                'app_name'        => $app_name,
                'language'        => $language,
                'currency'        => $currency,
                'currency_symbol' => $currency_symbol,
                'primary_color'   => '#c8860a',
                'accent_color'    => '#1a1a1a',
                'logo'            => '',
            ];
            $ins = $db->prepare("INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)");
            foreach ($defaults as $k => $v) {
                $ins->execute([$k, $v]);
            }

            // ── Create admin user ──
            $hash = password_hash($admin_pass, PASSWORD_DEFAULT);
            $db->prepare("INSERT INTO users (username, password) VALUES (?, ?)")
               ->execute([$admin_user, $hash]);

            // ── Write lock file ──
            file_put_contents(INSTALL_LOCK, date('Y-m-d H:i:s'));

            $success = true;

        } catch (Exception $e) {
            $errors[] = 'Database error: ' . $e->getMessage();
        }
    }
}

// ── Checks for step 1 display ──────────────────────────────────────────────
$checks = [
    'PHP ' . PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION . ' (need 7.4+)' =>
        PHP_VERSION_ID >= 70400,
    'PDO SQLite extension' =>
        extension_loaded('pdo_sqlite'),
    'Database folder writable (or creatable)' =>
        (is_dir(dirname(DB_PATH)) && is_writable(dirname(DB_PATH)))
        || (!is_dir(dirname(DB_PATH)) && is_writable(__DIR__)),
    'Assets folder writable' =>
        is_writable(__DIR__ . '/pages/assets'),
];
$allOk = !in_array(false, $checks, true);
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Restaurant POS — Install</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500&family=Playfair+Display:wght@700&display=swap" rel="stylesheet">
<style>
:root { --primary:#c8860a; --accent:#1a1a1a; }
body { font-family:'DM Sans',sans-serif; background:#f5f4f0; min-height:100vh; display:flex; align-items:center; justify-content:center; }
.install-wrap { width:100%; max-width:580px; padding:24px 16px; }
.install-card { background:#fff; border-radius:20px; box-shadow:0 4px 32px rgba(0,0,0,.08); overflow:hidden; }
.install-head { background:var(--accent); padding:36px 40px 28px; text-align:center; }
.install-head h1 { font-family:'Playfair Display',serif; color:#fff; font-size:1.8rem; margin:0 0 4px; }
.install-head p  { color:var(--primary); font-size:.8rem; letter-spacing:.1em; text-transform:uppercase; margin:0; }
.install-body { padding:36px 40px; }
.step-badge { display:inline-block; background:#f5f4f0; color:#888; font-size:.72rem; font-weight:600; letter-spacing:.08em; text-transform:uppercase; padding:4px 12px; border-radius:20px; margin-bottom:20px; }
.check-row { display:flex; align-items:center; gap:10px; padding:8px 0; font-size:.875rem; }
.check-row i.ok  { color:#16a34a; }
.check-row i.fail{ color:#e53935; }
.form-label { font-size:.82rem; font-weight:500; color:#555; }
.form-control, .form-select { border-radius:8px; border-color:#e8e5e0; font-size:.875rem; padding:9px 13px; }
.form-control:focus, .form-select:focus { border-color:var(--primary); box-shadow:0 0 0 3px rgba(200,134,10,.12); }
.btn-install { background:var(--primary); border:none; color:#fff; border-radius:10px; padding:13px; font-size:.95rem; font-weight:500; width:100%; cursor:pointer; }
.btn-install:disabled { opacity:.5; cursor:not-allowed; }
.btn-install:not(:disabled):hover { filter:brightness(1.08); }
.alert { border-radius:10px; font-size:.875rem; }
.success-icon { font-size:3rem; color:#16a34a; }
</style>
</head>
<body>
<div class="install-wrap">
  <div class="install-card">
    <div class="install-head">
      <h1>🍽 Restaurant POS</h1>
      <p>Installation Wizard</p>
    </div>
    <div class="install-body">

    <?php if ($success): ?>
      <!-- ── SUCCESS ── -->
      <div class="text-center">
        <div class="success-icon mb-3"><i class="bi bi-check-circle-fill"></i></div>
        <h4 style="font-weight:700;">Installation Complete!</h4>
        <p class="text-muted" style="font-size:.875rem;">
          Your SQLite database has been created at<br>
          <code>database/restaurant_pos.db</code>
        </p>
        <div class="alert alert-warning text-start mt-3">
          <i class="bi bi-shield-lock me-1"></i>
          <strong>Security note:</strong> For production, delete or restrict access to
          <code>install.php</code> to prevent re-installation.
        </div>
        <a href="index.php" class="btn-install d-block mt-3" style="text-decoration:none;text-align:center;line-height:1.6;">
          <i class="bi bi-arrow-right-circle me-1"></i> Go to Login
        </a>
      </div>

   <?php elseif ($step === 1): ?>
      <!-- ── STEP 1: Requirements ── -->
      <div class="step-badge">Step 1 of 2 — Requirements Check</div>
      <h5 style="font-weight:600;margin-bottom:4px;">System Requirements</h5>
      <p class="text-muted" style="font-size:.84rem;margin-bottom:20px;">
        Ensure the following checks pass before continuing.
      </p>

      <?php foreach ($checks as $label => $ok): ?>
        <div class="check-row">
          <i class="bi <?= $ok ? 'bi-check-circle-fill ok' : 'bi-x-circle-fill fail' ?>"></i>
          <span><?= htmlspecialchars($label) ?></span>
        </div>
      <?php endforeach; ?>

      <?php if (!$allOk): ?>
        <div class="alert alert-danger mt-3">
          Please fix the failing checks above before proceeding.
        </div>
      <?php endif; ?>

      <form method="POST" class="mt-4">
        <input type="hidden" name="step" value="2">
        <button type="submit" class="btn-install" <?= $allOk ? '' : 'disabled' ?>>
          Continue to Configuration <i class="bi bi-arrow-right ms-1"></i>
        </button>
      </form>

    <?php else: ?>
      <!-- ── STEP 2: Configuration ── -->
      <div class="step-badge">Step 2 of 2 — Configuration</div>
      <h5 style="font-weight:600;margin-bottom:4px;">Database &amp; App Setup</h5>
      <p class="text-muted" style="font-size:.84rem;margin-bottom:20px;">
        Configure your restaurant settings and admin account.
        <br><strong>No host or password needed</strong> — SQLite is a local file database.
      </p>

      <?php if (!empty($errors)): ?>
        <div class="alert alert-danger">
          <ul class="mb-0 ps-3">
            <?php foreach ($errors as $e): ?>
              <li><?= htmlspecialchars($e) ?></li>
            <?php endforeach; ?>
          </ul>
        </div>
      <?php endif; ?>

      <form method="POST" enctype="multipart/form-data">
        <input type="hidden" name="step" value="2">

        <h6 style="font-weight:600;margin:0 0 14px;color:#333;">🗃 Database</h6>
        <div class="alert alert-info" style="font-size:.82rem;">
          <i class="bi bi-database me-1"></i>
          A SQLite file will be created at <code>database/restaurant_pos.db</code>.
          No server configuration required — just PHP!
        </div>

        <h6 style="font-weight:600;margin:20px 0 14px;color:#333;">🌐 Base URL</h6>
        <div class="mb-3">
          <label class="form-label">
            App Base URL
            <span class="text-muted" style="font-weight:400;"> — the full URL where this app is installed</span>
          </label>
          <input type="url" name="base_url" class="form-control"
                 value="<?= htmlspecialchars($_POST['base_url'] ?? guessBaseUrl()) ?>"
                 placeholder="http://localhost/restaurant-sqlite"
                 required>
          <div class="form-text" style="font-size:.78rem;color:#999;margin-top:5px;">
            Examples: &nbsp;<code>http://localhost/myapp</code> &nbsp;·&nbsp; <code>https://pos.myrestaurant.com</code>
            <br>No trailing slash. This is used for all internal links and redirects.
          </div>
        </div>

        <h6 style="font-weight:600;margin:20px 0 14px;color:#333;">🏪 Restaurant</h6>
        <div class="mb-3">
          <label class="form-label">Restaurant Name</label>
          <input type="text" name="app_name" class="form-control"
                 value="<?= htmlspecialchars($_POST['app_name'] ?? 'My Restaurant') ?>" required>
        </div>
        <div class="row g-3 mb-3">
          <div class="col-6">
            <label class="form-label">Language</label>
            <select name="language" class="form-select">
              <option value="en" <?= ($_POST['language'] ?? 'en') === 'en' ? 'selected' : '' ?>>English</option>
              <option value="ar" <?= ($_POST['language'] ?? '') === 'ar' ? 'selected' : '' ?>>العربية</option>
            </select>
          </div>
          <div class="col-6">
            <label class="form-label">Currency</label>
            <select name="currency" class="form-select">
              <option value="USD" <?= ($_POST['currency'] ?? 'USD') === 'USD' ? 'selected' : '' ?>>USD — US Dollar</option>
              <option value="IQD" <?= ($_POST['currency'] ?? '') === 'IQD' ? 'selected' : '' ?>>IQD — دينار عراقي</option>
              <option value="SAR" <?= ($_POST['currency'] ?? '') === 'SAR' ? 'selected' : '' ?>>SAR — ريال سعودي</option>
              <option value="AED" <?= ($_POST['currency'] ?? '') === 'AED' ? 'selected' : '' ?>>AED — درهم اماراتي</option>
              <option value="EUR" <?= ($_POST['currency'] ?? '') === 'EUR' ? 'selected' : '' ?>>EUR — Euro</option>
              <option value="GBP" <?= ($_POST['currency'] ?? '') === 'GBP' ? 'selected' : '' ?>>GBP — British Pound</option>
            </select>
          </div>
        </div>

        <h6 style="font-weight:600;margin:20px 0 14px;color:#333;">👤 Admin Account</h6>
        <div class="mb-3">
          <label class="form-label">Username</label>
          <input type="text" name="admin_user" class="form-control"
                 value="<?= htmlspecialchars($_POST['admin_user'] ?? 'admin') ?>" required>
        </div>
        <div class="mb-3">
          <label class="form-label">Password <span class="text-muted">(min 4 chars)</span></label>
          <input type="password" name="admin_pass" class="form-control" required>
        </div>
        <div class="mb-4">
          <label class="form-label">Confirm Password</label>
          <input type="password" name="confirm_pass" class="form-control" required>
        </div>

        <button type="submit" class="btn-install">
          <i class="bi bi-database-add me-1"></i> Install Now
        </button>
      </form>
    <?php endif; ?>

    </div>
  </div>
  <p class="text-center text-muted mt-3" style="font-size:.75rem;">
    
<div class="container text-center fixed-bottom mw-100" style="font-size:.8rem;color:#aaa;padding:6px 0;">
  &copy; <?= date('Y') ?> &nbsp;|&nbsp;
  Developed by <a href="developer.php" style="color:#C8860A;text-decoration:none;font-weight:600;">A6h9</a>
</div>
  </p>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
